// <auto-generated />
using System;
using Forum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20240203002912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bff1d25-54e7-4850-9ac5-9b660e8f7d66"),
                            Content = "Just deployed a sleek new feature on my ASP.NET forum app - check it out and share your thoughts!",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("c21f0f6a-b06e-4054-9f3a-f2cdbf846afc"),
                            Content = "What's your go-to ASP.NET tip? Let's exchange some coding wisdom in our vibrant community!",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("8fec07f5-88c2-407c-b72c-3ab771f16f82"),
                            Content = "Facing a challenge in my ASP.NET project - seeking advice from fellow developers. Any insights appreciated!",
                            Title = "My third post"
                        },
                        new
                        {
                            Id = new Guid("d5696402-0413-43ac-a342-7930425705df"),
                            Content = "Exciting news! Our ASP.NET forum now supports real-time notifications. Stay connected with the latest discussions effortlessly!",
                            Title = "My fourth post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
